version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building the Maven WAR app..."
      - mvn clean install
  post_build:
    commands:
      - echo "Making Scripts executable"
      - chmod -R +x scripts/

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/*.sh
