version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building the Maven WAR app..."
      - mvn clean install

artifacts:
  files:
    - target/*.war
